APP/models.py
from flask_login import UserMixin
from flask_sqlalchemy import SQLAlchemy
from flask_wtf import FlaskForm
from werkzeug.security import generate_password_hash,check_password_hash
from wtforms import StringField, SubmitField, PasswordField
from wtforms.validators import DataRequired, Length, Email
from flask_wtf.file import FileField, FileRequired, FileAllowed
import cv2



db = SQLAlchemy()
def init_db(app):
    db.init_app(app)
    with app.app_context():
        db.create_all()


class User(UserMixin,db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.String(80), unique=True, nullable=False)
    password_hash = db.Column(db.String(255))

    @property
    def password(self):
        raise ArithmeticError('密码不可读取')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password_hash(self, password):
        return check_password_hash(self.password_hash, password)


class LoginForm(FlaskForm):
    user_id = StringField(u'用户名', validators=[
        DataRequired(message=u'用户名不能为空'), 
        Length(1,64)])
    password = PasswordField(u'密码', validators=[DataRequired(message=u'密码不能为空')])
    submit = SubmitField(u'登录')


class UploadForm(FlaskForm):
    file = FileField(label='上传视频或图片', 
    validators=[FileRequired(u'文件已上传')]
    )
    submit = SubmitField(u'上传')



class VideoCamera(object):
    def __init__(self):
        self.cap = cv2.VideoCapture('picture/y2mate.com - __VwoChR-3LLQ_360p.mp4')


    def __del__(self):
        self.cap.release()


    def get_frame(self):
        success, image = self.cap.read()
        ret, jpeg = cv2.imencode('.jpg', image)
        return jpeg.tobytes()

APP/__init__.py
import os 
from flask import Flask
from APP.views import init_blue, init_login
from APP.models import init_db
from flask_bootstrap import Bootstrap


def create_app():
    app = Flask(__name__)
    SQLALCHEMY_DATABASE_URI = 'sqlite:////' + os.path.join(app.root_path, 'data.db')
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    app.config['SECRET_KEY'] = 'dev'
    app.config['SQLALCHEMY_DATABASE_URI'] = SQLALCHEMY_DATABASE_URI
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] =SQLALCHEMY_TRACK_MODIFICATIONS


    init_blue(app)
    init_db(app)
    Bootstrap(app)
    init_login(app)
 

   

    return app

APP/views.py
from flask import *
from flask_login import LoginManager, current_user, login_required, login_user
from APP.models import User, LoginForm, UploadForm, VideoCamera
from werkzeug import secure_filename
# from flask_uploads import UploadSet, configure_uploads, IMAGES, patch_request_class

blue = Blueprint('first_blue', __name__)
def init_blue(app):
    app.register_blueprint(blueprint=blue)

login_manage = LoginManager()
def init_login(app):
    login_manage.login_view = 'first_blue.login'
    login_manage.login_message_category = 'info'
    login_manage.login_message = 'Access denied.'
    login_manage.init_app(app)


@login_manage.user_loader
def load_user(user_id):
    user = User.query.get(int(user_id))
    return user 


@login_manage.request_loader
def request_loader(request):
    pass

@blue.route('/')
@blue.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if request.method == 'POST':
        user_id = request.form.get('user_id')
        password = request.form.get('password')
        user = User.query.filter_by(user_id=user_id).first()
        if user is not None and user.check_password_hash(password):
            login_user(user)
            flash('Login success')
            return redirect(url_for('first_blue.detection'))
        flash('Invalid username or password.')
        
    
    return render_template('login.html',form=form)


@blue.route('/index')
def index():
    return render_template('index.html')


@blue.route('/detection',methods=['GET', 'POST'])
@login_required
def detection():
    form = UploadForm()
    if form.validate_on_submit():
        filename = secure_filename(form.file.data.filename)
        print(filename)
        form.file.data.save('picture/' + filename)
        flash('上传成功')
        return redirect('/detection')

    return render_template('detection.html', form=form)



@blue.route('/video')
def video():
    return render_template('video.html')

def gen(camera):
    while True:
        frame = camera.get_frame()
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')


@blue.route('/video_feed')
def video_feed():
    return Response(gen(VideoCamera()), 
    mimetype='multipart/x-mixed-replace; boundary=frame')

APP/templates/detection.html
{% extends 'bootstrap/base.html' %}
{% block styles %}
{{super()}}
<link rel="stylesheet"href="{{url_for('static', filename='style.css')}}">
{% endblock %}
{% block content %}
<body>
{% for message in get_flashed_messages() %}
<div class="alert">{{ message}}</div>
{% endfor %}
{% import 'bootstrap/wtf.html' as wtf %}
<form class="form" method="POST" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    {{ wtf.form_errors(form, hiddens="only") }}
    {{ wtf.form_field(form.file) }}
    {{ wtf.form_field(form.submit) }}
</form>
</div>

<img alt="Walking Totoro" class="totoro" src="{{ url_for('static', filename='logo.png') }}">
<footer>
    <small>&copy; 2018 <a href="http://helloflask.com/tutorial">HelloFlask</a></small>
</footer>
</body>
{% endblock %}

APP/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ name }}'s Watchlist</title>
    <link rel="icon" href="{{ url_for('static', filename='logo.png') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}" type="text/css">
</head>
<body>
    {% for message in get_flashed_messages() %}
    <div class="alert">{{ message }}</div>
    {% endfor %}
    <h2>
        <img alt="Avatar" class="avatar" src="{{ url_for('static', filename='logo.png') }}">
        {{ name }}'s Watchlist
    </h2>
    ...
    <ul class="movie-list">
        {% for movie in movies %}  {# 迭代 movies 变量 #}
        <li>{{ movie.title }} - {{ movie.year }}</li>  {# 等同于 movie['title'] #}
        {% endfor %}  {# 使用 endfor 标签结束 for 语句 #}
    </ul>
    <p>{{ movies|length }} Titles</p>
<form method="post">
    Name <input type="text" name="title" autocomplete="off" required>
    Year <input type="text" name="year" autocomplete="off" required>
    <input class="btn" type="submit" name="submit" value="Add">
</form>

    <img alt="Walking Totoro" class="totoro" src="{{ url_for('static', filename='logo.png') }}">
    <footer>
        <small>&copy; 2018 <a href="http://helloflask.com/tutorial">HelloFlask</a></small>
    </footer>
</body>
</html>

APP/templates/login.html
{% extends 'bootstrap/base.html' %}
<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ name }}'s Watchlist</title>
    <link rel="icon" href="{{ url_for('static', filename='logo.png') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}" type="text/css">
</head>

</html> -->

{% block styles %}
{{super()}}
<link rel="stylesheet"
      href="{{url_for('static', filename='style.css')}}">
{% endblock %}
{% block content %}
<body>
    {% for message in get_flashed_messages() %}
    <div class="alert">{{ message }}</div>
    {% endfor %}
    <div style="text-align: center;">
    {% import 'bootstrap/wtf.html' as wtf %}
    <form class="form" method="POST">
    {{ form.hidden_tag() }}
    {{ wtf.form_errors(form, hiddens="only") }}
    {{ wtf.form_field(form.user_id) }}
    {{ wtf.form_field(form.password) }}
    {{ wtf.form_field(form.submit) }}

    </form>
</div>

    <img alt="Walking Totoro" class="totoro" src="{{ url_for('static', filename='logo.png') }}">
    <footer>
        <small>&copy; 2018 <a href="http://helloflask.com/tutorial">HelloFlask</a></small>
    </footer>
</body>
{% endblock %}

APP/templates/video.html
{% extends 'bootstrap/base.html' %}
{% block styles %}
{{super()}}
<link rel="stylesheet"href="{{url_for('static', filename='style.css')}}">
{% endblock %}
{% block content %}
  <body>
    <div>
    <h1>Video Streaming Demonstration</h1>
    <img src="{{ url_for('first_blue.video_feed') }}">
  </div>
  </body>
<footer>
<img alt="Walking Totoro" class="totoro" src="{{ url_for('static', filename='logo.png') }}">
<small>&copy; 2020 <a href="#">BigData</a></small>
</footer>
</body>
{% endblock %}